// <auto-generated />
namespace HaftalikRapor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTableSecond : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTableSecond));
        
        string IMigrationMetadata.Id
        {
            get { return "202102161128146_updateTableSecond"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
